export const ACTIONS = {
    SET_STUDENTS: 'SET_STUDENTS',
    ADD_STUDENTS: 'ADD_STUDENTS',
    UPDATE_STUDENT: 'UPDATE_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    RESET_ERROR: 'RESET_ERROR'
};